---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: owncloud-apps
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./owncloud
  prune: true
  sourceRef:
    kind: GitRepository
    name: kube-learning-apps
    namespace: flux-system

