---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: owncloud-dev-apps
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./owncloud-manifests
  prune: true
  sourceRef:
    kind: GitRepository
    name: monacocloud-dev-apps
    namespace: flux-system

